import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from 'react'
import type { Workspace, Snapshot, Page, View, Selection, Plan, Operation, Check, Equipment } from './types'
import { kindNames, statusNames } from './types'
import { prepareExample, RULE_PACK, basis } from './domain'
import { useWorkspace, setSessionToken, request } from './store'
import { Button, Badge, Icon, Empty, Modal, Field, toneFor, dateText, timeText, localDate, exportJson } from './ui'
import { Inspector, Timeline, RelationshipGraph, History, EquipmentPicture } from './Views'
import { ApprovalForm, BranchForm, DocumentForm, EquipmentForm, LabForm, PlanForm, ReviewDocumentForm, TaskForm } from './Forms'
import example from '../../data/spatial-example.json'
const LabScene=lazy(()=>import('./Scene'))
const nav: {id:Page;label:string;icon:string;description:string}[]=[
 {id:'space',label:'空间',icon:'cube',description:'实验室空间'},
 {id:'plans',label:'计划',icon:'plans',description:'实验计划'},
 {id:'tasks',label:'协同',icon:'tasks',description:'待办与协作'},
 {id:'library',label:'资料',icon:'library',description:'资料与依据'},
 {id:'resources',label:'资源',icon:'resources',description:'实验室与资源'},
]
type Route={page:Page;view:View;labId:string;selection:Selection;planId:string;date:string}
function readRoute():Route {
 const q=new URLSearchParams(location.search),page=q.get('page') as Page,view=q.get('view') as View
 const [type,...parts]=(q.get('object')||'').split(':'),id=parts.join(':')
 return {page:[...nav.map(n=>n.id),'settings'].includes(page)?page:'space',view:['space','graph','time'].includes(view)?view:'space',labId:q.get('lab')||'',planId:q.get('plan')||'',date:/^\d{4}-\d{2}-\d{2}$/.test(q.get('date')||'')&&Number.isFinite(Date.parse(q.get('date')!))?q.get('date')!:localDate(),selection:id&&['equipment','plan','document','task'].includes(type)?{type:type as NonNullable<Selection>['type'],id}:null}
}
type Form={type:'lab'|'plan'|'equipment'|'document'|'task'|'branch'|'verify'|'approve';id?:string;planId?:string;equipmentId?:string}|null
export function WebWorkspace(){
 const api=useWorkspace(),{snapshot,busy,booting}=api,w=snapshot.workspace
 const [route,setRoute]=useState<Route>(readRoute),[form,setForm]=useState<Form>(null),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[expanded,setExpanded]=useState(true),[flat,setFlat]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[listOpen,setListOpen]=useState(false),[planFilter,setPlanFilter]=useState(''),[notice,setNotice]=useState('')
 const lab=w.laboratories.find(l=>l.id===route.labId)||w.laboratories[0],labId=lab?.id||''
 const plans=w.plans.filter(p=>p.labId===labId),equipment=w.equipment.filter(e=>e.labId===labId),checks=snapshot.checks.filter(c=>plans.some(p=>p.id===c.planId)),unresolved=checks.filter(c=>c.state!=='pass')
 const navigate=useCallback((change:Partial<Route>)=>{setRoute(prev=>{const next={...prev,...change},q=new URLSearchParams();q.set('page',next.page);q.set('view',next.view);if(next.labId)q.set('lab',next.labId);if(next.planId)q.set('plan',next.planId);if(next.selection)q.set('object',`${next.selection.type}:${next.selection.id}`);q.set('date',next.date);history.pushState(null,'',`${location.pathname}?${q}`);return next})},[])
 useEffect(()=>{const pop=()=>setRoute(readRoute());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[])
 useEffect(()=>{document.documentElement.dataset.motion=reduced?'reduced':'full';return()=>{delete document.documentElement.dataset.motion}},[reduced])
 const close=useCallback(()=>setForm(null),[]),select=(selection:Selection)=>navigate({selection,labId}),openPlan=(id:string)=>navigate({page:'plans',planId:id,selection:{type:'plan',id},labId:w.plans.find(p=>p.id===id)?.labId||labId})
 const act=async(op:Operation)=>{await api.mutate(op);setNotice('已保存，关联检查已重新计算。')}
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[notice])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[])
 const initialize=async()=>{try{await act({type:'initialize',payload:{workspace:prepareExample(example as Workspace,route.date)}});navigate({labId:'lab-201',selection:{type:'equipment',id:'F-01'},page:'space',view:'space'})}catch{}}
 const common={w,labId,mutate:act,onClose:close,onLabCreated:(id:string)=>{setListOpen(true);navigate({page:'space',view:'space',labId:id,planId:'',selection:null});setNotice('实验室已建立，已切换到新空间。')},onEquipmentCreated:(id:string)=>{navigate({page:'space',view:'space',labId,planId:'',selection:{type:'equipment',id}});setListOpen(false);setNotice('资源已加入空间并自动定位。')}}
 const inspector=<Inspector key={`${route.selection?.type}:${route.selection?.id}`} snapshot={snapshot} selection={route.selection} onSelect={select} onOpenPlan={openPlan} onTask={(planId,equipmentId)=>setForm({type:'task',planId,equipmentId})} onDocument={()=>setForm({type:'document',equipmentId:route.selection?.type==='equipment'?route.selection.id:undefined})} onEditEquipment={id=>setForm({type:'equipment',id})} onBranch={id=>setForm({type:'branch',id})} onReviewDocument={id=>setForm({type:'verify',id})}/>
 const currentPlan=w.plans.find(p=>p.id===route.planId)
 return <div className={`al-shell ${expanded?'nav-expanded':''}`}>
  <aside className="al-rail"><a className="al-brand" href="?page=space" aria-label="AegisLab 首页"><span><Icon name="shield" size={25}/></span>{expanded&&<b>AegisLab</b>}</a><button className="al-rail-toggle" title={expanded?'收起导航':'展开导航'} onClick={()=>setExpanded(!expanded)}><Icon name="layout" size={18}/>{expanded&&<span>收起导航</span>}</button><nav aria-label="主要导航">{nav.map(n=><button key={n.id} className={route.page===n.id?'active':''} aria-current={route.page===n.id?'page':undefined} title={n.description} onClick={()=>{navigate({page:n.id,...(n.id==='plans'?{planId:''}:{})});setQuery('')}}><Icon name={n.icon} size={23}/><span>{expanded?n.description:n.label}</span>{n.id==='tasks'&&w.tasks.some(t=>t.status!=='done')&&<i className="al-nav-dot"/>}</button>)}</nav><div className="al-rail-bottom"><button title="工作区设置" className={route.page==='settings'?'active':''} onClick={()=>navigate({page:'settings'})}><Icon name="settings" size={23}/><span>{expanded?'工作区设置':'设置'}</span></button><div className="al-avatar" title="工作区操作记录，不代表机构身份认证">A</div></div></aside>
  <div className="al-main"><header className="al-topbar"><div className="al-wordmark">Aegis<span>Lab</span><small>实验安全协同工作台</small></div><span className="al-top-divider"/><div className="al-workspace-name"><Icon name="layer" size={17}/><span>{w.name}</span><Icon name="chevron" size={13}/></div><select className="al-lab-select" aria-label="选择实验室" value={labId} onChange={e=>navigate({labId:e.target.value,selection:null,planId:''})}>{!labId&&<option value="">尚未配置实验室</option>}{w.laboratories.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><div className="al-top-right"><button className="al-search-trigger" onClick={()=>setSearchOpen(true)}><Icon name="search" size={17}/><span>搜索计划、设备、依据</span><kbd>⌘ K</kbd></button><Button icon="bell" title="查看待处理协作任务" onClick={()=>navigate({page:'tasks'})}/><div className="al-account"><span className="al-avatar small">A</span><div><b>工作区访问者</b><small>{snapshot.mode==='server'?'服务端连接':'浏览器草稿'}</small></div></div></div></header>
  <div className="al-state-strip"><span className={`al-connection ${snapshot.mode==='server'?'connected':''}`}><i/>{booting?'正在检查连接':api.connection}</span><span>工作区 v{w.revision}</span>{w.provenance==='example'&&<Badge tone="amber">示例数据 · 非现场记录</Badge>}<span className="al-strip-note">AI 辅助理解 · 规则核验 · 人工复核</span>{busy&&<span className="al-save-progress">保存中…</span>}</div>
  {api.error&&<div role="alert" className="al-global-error"><Icon name="alert" size={18}/><span>{api.error}</span><Button onClick={()=>api.setError('')} title="收起错误提示" icon="close"/></div>}
  {!lab&&route.page!=='settings'?<div className="al-onboarding"><span className="al-onboarding-symbol"><Icon name="cube" size={52}/></span><span className="al-eyebrow">YOUR LAB. CONNECTED.</span><h1>让实验计划，与真实条件连接。</h1><p>从一间实验室开始，把设备、使用时段与检查依据放在同一个工作区。<br/>这是浏览器里的网页系统，无需安装客户端。</p><div className="al-onboarding-actions"><Button primary icon="plus" disabled={booting||busy} onClick={()=>setForm({type:'lab'})}>建立我的实验室</Button><Button icon="layer" disabled={booting||busy} onClick={initialize}>导入示例工作区</Button></div><div className="al-onboarding-notes"><div><Icon name="cube"/><b>空间可操作</b><span>点击设备，查看关系与依据。</span></div><div><Icon name="graph"/><b>变化可解释</b><span>同一组约束，比较不同安排。</span></div><div><Icon name="shield"/><b>决策可追溯</b><span>保留版本、来源与人工记录。</span></div></div><small>示例工作区需要主动导入，所有示例数据持续标记；它不是自动播放的比赛演示。</small></div>:
  route.page==='space'?<div className="al-spatial-shell"><div className="al-space-primary"><div className="al-space-toolbar"><div className="al-space-title"><Icon name="cube" size={20}/><h1>{lab.name}</h1><span>{equipment.length} 项资源</span></div><div className="al-segment" role="tablist" aria-label="实验室视图">{([['space','cube','空间'],['graph','graph','关系'],['time','clock','时间']] as const).map(([id,icon,text])=><button key={id} role="tab" aria-selected={route.view===id} className={route.view===id?'active':''} onClick={()=>navigate({view:id})}><Icon name={icon} size={16}/>{text}</button>)}</div><Button icon="plus" primary onClick={()=>setForm({type:'plan'})}>新建计划</Button></div>
  <div className="al-space-context"><select aria-label="筛选当前计划" value={route.planId} onChange={e=>navigate({planId:e.target.value,selection:e.target.value?{type:'plan',id:e.target.value}:null})}><option value="">全部实验计划</option>{plans.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><button className="al-attention-chip" onClick={()=>{setPlanFilter('unresolved');navigate({page:'plans',planId:''})}}><Icon name="alert" size={15}/>{unresolved.length} 项待处理</button><span className="al-space-context-spacer"/>{route.view==='space'&&<><Button icon="eye" onClick={()=>setFlat(!flat)}>{flat?'三维空间':'二维平面'}</Button><Button icon="filter" onClick={()=>setListOpen(!listOpen)}>对象清单</Button></>}</div>
  {route.view==='space'&&<SpaceKpis plans={plans} checks={checks} equipment={equipment} onPlans={()=>navigate({page:'plans',planId:''})} onConflicts={()=>navigate({page:'plans',planId:''})} />}
  <div className="al-space-content">{route.view==='space'?<><Suspense fallback={<div className="al-loading"><span/>正在载入实验室空间…</div>}><LabScene lab={lab} equipment={equipment} plans={plans} checks={checks} selection={route.selection} planId={route.planId} onSelect={select} reduced={reduced} flat={flat}/></Suspense>{listOpen&&<div className="al-object-list"><header><b>实验室对象</b><Button icon="close" title="关闭对象清单" onClick={()=>setListOpen(false)}/></header>{equipment.map(e=><button key={e.id} className={route.selection?.id===e.id?'selected':''} onClick={()=>select({type:'equipment',id:e.id})}><Icon name="resources" size={17}/><span><b>{e.name}</b><small>{e.code} · {kindNames[e.kind]}</small></span><Icon name="chevron" size={14}/></button>)}<Button icon="plus" onClick={()=>setForm({type:'equipment'})}>添加资源</Button></div>}<div className="al-space-legend"><span><i className="blue"/>当前关联</span><span><i className="amber"/>待核验</span><span><i className="red"/>约束冲突</span><span>连线 = 计划使用关系</span></div></>:route.view==='graph'?<RelationshipGraph snapshot={snapshot} labId={labId} selection={route.selection} onSelect={select}/>:<div className="al-time-page"><div className="al-view-toolbar"><div><span className="al-eyebrow">RESOURCE SCHEDULE</span><h2>把计划放在同一条时间线上</h2><p>查阅共享资源、维护与占用安排，选择计划后比较变更方案。</p></div><input aria-label="时间视图日期" type="date" value={route.date} onChange={e=>e.target.value&&navigate({date:e.target.value})}/></div><Timeline workspace={w} labId={labId} date={route.date} selection={route.selection} onSelect={select}/></div>}</div>
  {route.view==='space'&&<SpaceDock plans={plans} equipment={equipment} workspace={w} labId={labId} date={route.date} selection={route.selection} onSelect={select} onOpenTime={()=>navigate({view:'time'})} onOpenGraph={()=>navigate({view:'graph'})}/>}</div>{inspector}</div>:
  route.page==='plans'?<div className="al-content-page">{currentPlan&&currentPlan.labId===labId?<PlanDetail key={currentPlan.id} plan={currentPlan} snapshot={snapshot} onBack={()=>navigate({planId:''})} mutate={act} onEdit={()=>setForm({type:'plan',id:currentPlan.id})} onBranch={()=>setForm({type:'branch',id:currentPlan.id})} onApproval={()=>setForm({type:'approve',id:currentPlan.id})} onTask={()=>setForm({type:'task',planId:currentPlan.id})} onSelect={s=>navigate({page:'space',view:'space',selection:s})}/>:<><PageTitle eyebrow="EXPERIMENT PLANS" title="实验计划" detail="把原文、使用安排与待处理问题放回同一项实验。" action={<Button primary icon="plus" onClick={()=>setForm({type:'plan'})}>新建实验计划</Button>}/><div className="al-summary-row">{[['全部计划',String(plans.length),'plans'],['存在阻断',String(plans.filter(p=>snapshot.statuses[p.id]==='blocked').length),'alert'],['待复核',String(plans.filter(p=>snapshot.statuses[p.id]==='ready').length),'shield'],['待补证 / 确认',String(plans.filter(p=>['draft','unknown','recheck'].includes(snapshot.statuses[p.id])).length),'file']].map(([label,value,icon])=><div key={label}><span><Icon name={icon}/>{label}</span><b>{value.padStart(2,'0')}</b></div>)}</div><div className="al-table-panel"><div className="al-table-toolbar"><div className="al-filter-tabs">{[['','全部'],['unresolved','待处理'],['ready','待复核'],['approved','已记录复核']].map(([v,l])=><button key={v} className={planFilter===v?'active':''} onClick={()=>setPlanFilter(v)}>{l}</button>)}</div><Search value={query} onChange={setQuery} placeholder="搜索计划或负责人"/></div><table className="al-table"><thead><tr><th>实验计划</th><th>当前状态</th><th>负责人</th><th>版本 / 步骤</th><th>未决项</th><th>操作</th></tr></thead><tbody>{plans.filter(p=>(`${p.name} ${p.code} ${p.owner}`).includes(query)&&(!planFilter||(planFilter==='unresolved'?['draft','blocked','unknown','recheck'].includes(snapshot.statuses[p.id]):snapshot.statuses[p.id]===planFilter))).map(p=><tr key={p.id}><td><button className="al-table-title" onClick={()=>openPlan(p.id)}><span className="al-mini-icon"><Icon name="flask"/></span><div><b>{p.name}</b><small>{p.code} · {p.sourceName}</small></div></button></td><td><Badge tone={toneFor(snapshot.statuses[p.id])}>{statusNames[snapshot.statuses[p.id]]}</Badge></td><td>{p.owner}</td><td>v{p.revision} <span className="al-muted">/ {p.steps.length} 步</span></td><td>{checks.filter(c=>c.planId===p.id&&c.state!=='pass').length}</td><td><Button icon="arrow" title={`打开 ${p.name}`} onClick={()=>openPlan(p.id)}/></td></tr>)}</tbody></table>{!plans.length&&<Empty title="还没有实验计划" detail="导入或粘贴计划原文，设置使用资源后即可开始核验。"/>}</div><div className="al-page-footnote"><Icon name="info" size={16}/>当前检查范围：原文确认、资源容量、维护窗口与检查证据；不以“通过”标签替代机构安全审查。</div></>}</div>:
  route.page==='tasks'?<div className="al-content-page"><PageTitle eyebrow="COLLABORATION" title="让每个问题，都有下一步。" detail="补什么、谁负责、何时完成。任务进度与证据核验分开记录。" action={<Button primary icon="plus" onClick={()=>setForm({type:'task'})}>创建任务</Button>}/><div className="al-kanban">{(['open','submitted','done'] as const).map(state=><section key={state}><header><Badge tone={state==='open'?'amber':state==='submitted'?'blue':'green'}>{{open:'待处理',submitted:'待核验',done:'已完成'}[state]}</Badge><span>{w.tasks.filter(t=>t.status===state).length}</span></header>{w.tasks.filter(t=>t.status===state).map(t=><button className="al-task-card" key={t.id} onClick={()=>setForm({type:'task',id:t.id})}><small>{t.planId||'工作区任务'}</small><h3>{t.title}</h3><p>{t.note||'点击填写处理记录。'}</p>{t.equipmentId&&<span className="al-object-pill"><Icon name="resources" size={14}/>{t.equipmentId}</span>}<footer><span><i className="al-person-dot">{t.owner.slice(0,1)}</i>{t.owner}</span><span className={state!=='done'&&Date.parse(t.dueAt)<Date.now()?'al-overdue':''}><Icon name="clock" size={14}/>{dateText(t.dueAt)}</span></footer></button>)}{!w.tasks.some(t=>t.status===state)&&<div className="al-kanban-empty">此列暂无任务</div>}</section>)}</div></div>:
  route.page==='library'?<div className="al-split-page"><div className="al-content-page"><PageTitle eyebrow="DOCUMENTS & EVIDENCE" title="资料与依据" detail="资料有来源、版本和适用范围；上传并不意味着核验通过。" action={<Button primary icon="plus" onClick={()=>setForm({type:'document'})}>添加资料</Button>}/><div className="al-table-panel"><div className="al-table-toolbar"><span>{w.documents.length} 份资料</span><Search value={query} onChange={setQuery} placeholder="搜索资料名称、来源"/></div><table className="al-table"><thead><tr><th>资料名称</th><th>状态</th><th>适用截止</th></tr></thead><tbody>{w.documents.filter(d=>(d.name+' '+d.source).includes(query)).map(d=><tr key={d.id} className={route.selection?.id===d.id?'selected':''}><td><button className="al-table-title" onClick={()=>select({type:'document',id:d.id})}><span className="al-mini-icon"><Icon name="file"/></span><div><b>{d.name}</b><small>{d.equipmentId||'通用资料'} · 规格 v{d.specVersion}</small></div></button></td><td><Badge tone={toneFor(d.status)}>{{pending:'待核验',verified:'已核验',rejected:'已退回'}[d.status]}</Badge></td><td>{dateText(d.validUntil)}</td></tr>)}</tbody></table>{!w.documents.length&&<Empty title="尚无资料" detail="添加有明确来源的 SOP、参考文件和检查记录。"/>}</div></div>{inspector}</div>:
  route.page==='resources'?<div className="al-content-page"><PageTitle eyebrow="LABORATORIES & RESOURCES" title="实验室与资源" detail="这里的设备与空间中的对象一一对应；位置变化不会被误认为能力变化。" action={<><Button icon="plus" onClick={()=>setForm({type:'lab'})}>建立实验室</Button><Button primary icon="plus" onClick={()=>setForm({type:'equipment'})}>添加资源</Button></>}/><div className="al-resource-summary"><div><Icon name="cube" size={27}/><div><h3>{lab.name}</h3><p>{lab.description}</p></div></div><span>{lab.width} × {lab.depth} m <span className="al-muted">场景尺寸</span></span><Button icon="arrow" onClick={()=>navigate({page:'space',view:'space'})}>进入空间</Button></div><div className="al-resource-grid">{equipment.map(e=><article className="al-resource-card" key={e.id}><EquipmentPicture equipment={e}/><div><span className="al-eyebrow">{e.code} / {kindNames[e.kind]}</span><h3>{e.name}</h3><Badge tone={e.status==='unknown'?'amber':e.status==='unavailable'?'red':'blue'}>{{unknown:'台账待确认',available:'登记可用',unavailable:'登记停用'}[e.status]}</Badge><p>{e.owner||'未指定负责人'} · 规格 v{e.specVersion}</p></div><footer><Button icon="edit" onClick={()=>setForm({type:'equipment',id:e.id})}>编辑资料</Button><Button icon="target" onClick={()=>navigate({page:'space',view:'space',selection:{type:'equipment',id:e.id}})}>空间定位</Button></footer></article>)}</div>{!equipment.length&&<Empty title="添加你的第一项资源" detail="设备模型由台账数据驱动，支持位置、朝向、容量和维护窗口。"/>}</div>:
  <Settings api={api} reduced={reduced} setReduced={setReduced} w={w} onInitialize={initialize} onAddLab={()=>setForm({type:'lab'})}/>
  }</div>
  {form?.type==='lab'&&<LabForm {...common}/>} {form?.type==='plan'&&<PlanForm {...common} plan={w.plans.find(p=>p.id===form.id)}/>}{form?.type==='equipment'&&<EquipmentForm {...common} equipment={w.equipment.find(e=>e.id===form.id)}/>}{form?.type==='document'&&<DocumentForm {...common} equipmentId={form.equipmentId}/>} {form?.type==='task'&&<TaskForm {...common} planId={form.planId} equipmentId={form.equipmentId} task={w.tasks.find(t=>t.id===form.id)}/>} {form?.type==='branch'&&w.plans.some(p=>p.id===form.id)&&<BranchForm {...common} plan={w.plans.find(p=>p.id===form.id)!}/>} {form?.type==='verify'&&<ReviewDocumentForm {...common} id={form.id!}/>} {form?.type==='approve'&&<ApprovalForm {...common} plan={w.plans.find(p=>p.id===form.id)!} server={snapshot.mode==='server'}/>}
  {searchOpen&&<SearchModal w={w} onClose={()=>setSearchOpen(false)} onSelect={s=>{const p=s.type==='plan'?w.plans.find(p=>p.id===s.id):null;const e=s.type==='equipment'?w.equipment.find(e=>e.id===s.id):null;navigate({page:p?'plans':s.type==='document'?'library':s.type==='task'?'tasks':'space',selection:s,labId:p?.labId||e?.labId||labId,planId:p?.id||''});setSearchOpen(false)}}/>}
  {notice&&<div className="al-toast" role="status"><Icon name="check" size={17}/>{notice}</div>}
 </div>
}
function PageTitle({eyebrow,title,detail,action}:{eyebrow:string;title:string;detail:string;action?:React.ReactNode}){return <div className="al-page-title"><div><span className="al-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{detail}</p></div><div className="al-actions">{action}</div></div>}
function Search({value,onChange,placeholder}:{value:string;onChange:(s:string)=>void;placeholder:string}){return <label className="al-search"><Icon name="search" size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder}/></label>}
function SearchModal({w,onClose,onSelect}:{w:Workspace;onClose:()=>void;onSelect:(s:NonNullable<Selection>)=>void}){const [q,setQ]=useState('');const rows=[...w.equipment.map(e=>({type:'equipment' as const,id:e.id,name:e.name,detail:e.code,icon:'resources'})),...w.plans.map(p=>({type:'plan' as const,id:p.id,name:p.name,detail:p.code,icon:'plans'})),...w.documents.map(d=>({type:'document' as const,id:d.id,name:d.name,detail:d.source,icon:'file'})),...w.tasks.map(t=>({type:'task' as const,id:t.id,name:t.title,detail:t.owner,icon:'tasks'}))].filter(x=>(x.name+' '+x.detail).toLowerCase().includes(q.toLowerCase())).slice(0,16);return <Modal title="搜索工作区" onClose={onClose}><div className="al-form-body"><Search value={q} onChange={setQ} placeholder="输入名称、编号、来源或负责人"/><div className="al-search-results">{rows.map(r=><button key={r.type+r.id} onClick={()=>onSelect({type:r.type,id:r.id})}><Icon name={r.icon}/><div><b>{r.name}</b><small>{r.detail}</small></div><Icon name="arrow" size={17}/></button>)}{!rows.length&&<Empty title="没有匹配的对象" detail="尝试另一个名称或编号。"/>}</div></div></Modal>}

function SpaceKpis({plans,checks,equipment,onPlans,onConflicts}:{plans:Plan[];checks:Check[];equipment:Equipment[];onPlans:()=>void;onConflicts:()=>void}) {
 const unresolved=checks.filter(c=>c.state!=='pass'),blocked=checks.filter(c=>c.state==='blocked')
 const released=plans.filter(p=>{const own=checks.filter(c=>c.planId===p.id);return own.length>0&&own.every(c=>c.state==='pass')}).length
 const used=new Set(plans.flatMap(p=>p.reservations.map(r=>r.equipmentId))).size
 const usage=equipment.length?Math.round(used/equipment.length*100):0
 const state=blocked.length?'需处理':unresolved.length?'待复核':'可继续'
 const cards=[
  {label:'待处理实验',value:String(plans.filter(p=>checks.some(c=>c.planId===p.id&&c.state!=='pass')).length),hint:`${unresolved.length} 项未决`,icon:'plans',tone:'blue',onClick:onPlans},
  {label:'风险阻断项',value:String(blocked.length),hint:blocked.length?'需要定位冲突':'当前无硬阻断',icon:'alert',tone:'red',onClick:onConflicts},
  {label:'已完成核验',value:String(released),hint:`共 ${plans.length} 项计划`,icon:'check',tone:'green',onClick:onPlans},
  {label:'资源覆盖率',value:`${usage}%`,hint:`${used} / ${equipment.length} 项被计划使用`,icon:'resources',tone:'blue',onClick:onPlans},
  {label:'实验室状态',value:state,hint:'来自当前快照与规则结果',icon:'shield',tone:blocked.length?'amber':'green',onClick:onConflicts},
 ] as const
 return <div className="al-space-kpis" aria-label="实验室运行概览">{cards.map(card=><button className={`al-space-kpi ${card.tone}`} key={card.label} onClick={card.onClick}><span className="al-space-kpi-icon"><Icon name={card.icon} size={17}/></span><span className="al-space-kpi-copy"><small>{card.label}</small><strong>{card.value}</strong><em>{card.hint}</em></span><Icon name="arrow" size={14}/></button>)}</div>
}

function SpaceDock({plans,equipment,workspace,labId,date,selection,onSelect,onOpenTime,onOpenGraph}:{plans:Plan[];equipment:Equipment[];workspace:Workspace;labId:string;date:string;selection:Selection;onSelect:(s:Selection)=>void;onOpenTime:()=>void;onOpenGraph:()=>void}) {
 const related=plans.filter(p=>!p.archived).slice().sort((a,b)=>Date.parse(a.reservations[0]?.start||'')-Date.parse(b.reservations[0]?.start||'')).slice(0,3)
 const graphEquipment=equipment.filter(e=>plans.some(p=>p.reservations.some(r=>r.equipmentId===e.id))).slice(0,4)
 return <section className="al-space-dock" aria-label="实验室运行详情">
  <article className="al-dock-card al-dock-plans"><header><div><span className="al-eyebrow">REVIEW QUEUE</span><h3>相关实验计划</h3></div><button onClick={onOpenTime}>查看全部 <Icon name="arrow" size={14}/></button></header><div className="al-dock-plan-list">{related.map((p,i)=><button key={p.id} onClick={()=>onSelect({type:'plan',id:p.id})}><span className={`al-dock-plan-icon tone-${i%3}`}><Icon name="flask" size={17}/></span><span><b>{p.code}</b><small>{p.name}</small><em>{p.reservations.length} 项资源 · {p.owner}</em></span><Icon name="chevron" size={14}/></button>)}{!related.length&&<Empty title="暂无相关计划" detail="计划登记资源后会出现在这里。"/>}</div></article>
  <article className="al-dock-card al-dock-time"><header><div><span className="al-eyebrow">RESOURCE TIMELINE</span><h3>设备时间轴</h3></div><button onClick={onOpenTime}><input aria-label="计划安排日期" type="date" value={date} readOnly/> <Icon name="arrow" size={14}/></button></header><Timeline compact workspace={workspace} labId={labId} date={date} selection={selection} onSelect={onSelect}/></article>
  <article className="al-dock-card al-dock-graph"><header><div><span className="al-eyebrow">DEPENDENCY MAP</span><h3>关联关系图谱</h3></div><button onClick={onOpenGraph}>打开图谱 <Icon name="arrow" size={14}/></button></header><div className="al-dock-network"><div className="al-dock-node primary"><Icon name="flask" size={16}/><span>实验计划</span></div><div className="al-dock-lines">{graphEquipment.map(e=><i key={e.id}/>)}</div><div className="al-dock-node-list">{graphEquipment.slice(0,3).map(e=><button key={e.id} onClick={()=>onSelect({type:'equipment',id:e.id})}><span className="al-dock-dot"/><b>{e.code}</b><small>{e.name}</small></button>)}{!graphEquipment.length&&<span className="al-muted">选择计划后显示资源关系</span>}</div></div></article>
 </section>
}

interface CopilotItem {id:string;title:string;detail:string;severity?:string;step?:number|null;controls?:string[];ppe?:string[];evidence?:string[];equipmentId?:string|null;line?:number|null;documentIds?:string[];relatedPlanIds?:string[];priority?:string;sourceId?:string;owner?:string}
interface CopilotScenario {id:string;name:string;kind:string;status:string;summary:string;counts:{blocked:number;unknown:number;pass:number};changes:Record<string,unknown>[]}
interface CopilotPacket {entities:{steps:number;hazards:CopilotItem[];substances:Record<string,unknown>[];ppe:string[];equipment:string[];wasteStreams:string[];ventilation:string|null};riskSignals:CopilotItem[];conflicts:CopilotItem[];evidenceGaps:CopilotItem[];nextActions:CopilotItem[];scenarios:CopilotScenario[];ruleSummary:{total:number;blocked:number;unknown:number;pass:number;failedTextRules:string[]}}
interface Analysis {planId:string;planRevision:number;ruleVersion:string;parser:string;provider:string;model?:string|null;degraded:boolean;summary:string;results:{rule_id:string;passed:boolean;message:string;recommended_control?:string;rule_version:string;source?:string}[];copilot?:CopilotPacket}
function PlanDetail({plan:p,snapshot,mutate,onBack,onEdit,onBranch,onApproval,onTask,onSelect}:{plan:Plan;snapshot:Snapshot;mutate:(op:Operation)=>Promise<void>;onBack:()=>void;onEdit:()=>void;onBranch:()=>void;onApproval:()=>void;onTask:()=>void;onSelect:(s:Selection)=>void}){
 const w=snapshot.workspace,[tab,setTab]=useState('review'),[line,setLine]=useState<number|null>(null),[analysis,setAnalysis]=useState<Analysis|null>(null),[analyzing,setAnalyzing]=useState(false),[error,setError]=useState('')
 const checks=snapshot.checks.filter(c=>c.planId===p.id),status=snapshot.statuses[p.id]
 const run=async(op:Operation)=>{setError('');try{await mutate(op)}catch(e){setError(e instanceof Error?e.message:'操作未完成。')}}
 const analyze=async()=>{setError('');setAnalyzing(true);try{const response=await request<Analysis>(`/api/spatial/plans/${encodeURIComponent(p.id)}/analysis`,{});setAnalysis(response)}catch(e){setError(e instanceof Error?e.message:'预审未完成。')}finally{setAnalyzing(false)}}
 const openCopilot=()=>{setTab('analysis');if(!analysis&&!analyzing&&snapshot.mode==='server')void analyze()}
 useEffect(()=>{if(line)document.getElementById(`source-line-${line}`)?.scrollIntoView({block:'center',behavior:'smooth'})},[line])
 return <><button className="al-back" onClick={onBack}><Icon name="back" size={17}/>全部实验计划</button><PageTitle eyebrow={`${p.code} / REVISION ${p.revision}`} title={p.name} detail={`${p.owner} · ${w.laboratories.find(l=>l.id===p.labId)?.name} · ${p.sourceName}`} action={<><Button primary icon="spark" onClick={openCopilot}>{analysis?'查看 AI Copilot':'运行 AI Copilot'}</Button><Button icon="edit" onClick={onEdit}>编辑计划</Button><Button icon="graph" onClick={onBranch}>比较变更方案</Button><Button primary icon="shield" onClick={onApproval}>人工复核</Button></>}/><div className="al-plan-status"><Badge tone={toneFor(status)}>{statusNames[status]}</Badge><span>{checks.filter(c=>c.state==='blocked').length} 项阻断 <i/> {checks.filter(c=>c.state==='unknown').length} 项待确认</span><span>规则包 {RULE_PACK}</span><Button icon="export" onClick={()=>exportJson({scope:'资源前置条件记录，非安全证书',exportedAt:new Date().toISOString(),plan:p,checks,decisions:w.decisions.filter(d=>d.planId===p.id),events:w.events.filter(e=>e.objectId===p.id)},`${p.code}-review.json`)}>导出记录</Button></div>
 <div className="al-plan-tabs">{[['review','原文与检查'],['schedule','资源安排'],['analysis','AI Copilot'],['branches',`已存方案 ${w.branches.filter(b=>b.planId===p.id).length}`],['history','决策与历史']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<div className="al-form-error" role="alert">{error}</div>}
 {tab==='review'&&<div className="al-review-grid"><section className="al-source-panel"><header><div><Icon name="file" size={18}/><b>计划原文</b></div><small>{p.sourceName}</small></header><div className="al-source-lines">{p.source.split(/\r?\n/).map((text,i)=><div id={`source-line-${i+1}`} key={i} className={line===i+1?'highlight':''}><span>{String(i+1).padStart(2,'0')}</span><p>{text||' '}</p></div>)}</div><footer><Badge tone={p.steps.every(s=>s.confirmed)?'blue':'amber'}>{p.steps.every(s=>s.confirmed)?'步骤已人工确认':'步骤待确认'}</Badge>{p.steps.some(s=>!s.confirmed)&&<Button icon="check" onClick={()=>run({type:'confirm_steps',payload:{planId:p.id}})}>核对后确认全部步骤</Button>}</footer><div className="al-section-label">结构化步骤 / {p.steps.length}</div><div className="al-step-list">{p.steps.map((s,i)=><button key={s.id} className={line===s.line?'active':''} onClick={()=>setLine(s.line)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s.text}</b><small>原文 L{s.line} · {s.equipmentIds.map(id=>w.equipment.find(e=>e.id===id)?.code||id).join('、')||'未匹配资源'}</small></div><Icon name={s.confirmed?'check':'info'} size={16}/></button>)}</div></section><section className="al-check-panel"><header><div><span className="al-eyebrow">CHECKS & NEXT ACTION</span><h2>从问题，回到依据。</h2></div><Button icon="plus" onClick={onTask}>补证任务</Button></header><div className="al-checks-list">{checks.slice().sort((a,b)=>({blocked:0,unknown:1,pass:2}[a.state]-{blocked:0,unknown:1,pass:2}[b.state])).map(c=><article className={`al-finding-card ${c.state}`} key={c.id}><div><span className={`al-finding-icon ${c.state}`}><Icon name={c.state==='pass'?'check':'alert'} size={17}/></span><h3>{c.title}</h3><Badge tone={toneFor(c.state)}>{{pass:'满足',unknown:'未知',blocked:'阻断'}[c.state]}</Badge></div><p>{c.detail}</p><footer><small>{c.code} · {RULE_PACK}</small><div>{c.line&&<button onClick={()=>{setTab('review');setLine(c.line)}}>原文 L{c.line}</button>}{c.equipmentId&&<button onClick={()=>onSelect({type:'equipment',id:c.equipmentId!})}>关联资源 <Icon name="arrow" size={13}/></button>}</div></footer>{c.documentIds.length>0&&<div className="al-check-docs">{c.documentIds.map(id=><button key={id} onClick={()=>onSelect({type:'document',id})}><Icon name="file" size={13}/>{w.documents.find(d=>d.id===id)?.name||id}</button>)}</div>}</article>)}</div></section></div>}
 {tab==='schedule'&&<section className="al-table-panel"><div className="al-table-toolbar"><h3>计划内的资源使用安排</h3><Button icon="graph" onClick={onBranch}>比较调整方案</Button></div><table className="al-table"><thead><tr><th>使用资源</th><th>开始时间</th><th>结束时间</th><th>查看对象</th></tr></thead><tbody>{p.reservations.map(r=><tr key={r.id}><td>{w.equipment.find(e=>e.id===r.equipmentId)?.name} <small>{r.equipmentId}</small></td><td>{dateText(r.start)}</td><td>{dateText(r.end)}</td><td><Button icon="target" onClick={()=>onSelect({type:'equipment',id:r.equipmentId})}>空间定位</Button></td></tr>)}</tbody></table>{!p.reservations.length&&<Empty title="尚未安排资源" detail="通过编辑计划添加设备和使用时段；系统不会把缺失条件判断为满足。"/>}</section>}
 {tab==='analysis'&&<section className="al-analysis"><div className="al-analysis-heading"><span><Icon name="spark" size={26}/></span><div><h2>AI Copilot · 从 SOP 到放行建议</h2><p>把原文拆成步骤、风险、证据缺口和可比较方案。AI 只解释与提出候选，规则结果和人工复核仍是放行闸门。</p></div><Button primary icon="spark" disabled={analyzing||snapshot.mode!=='server'} onClick={analyze}>{analyzing?'正在解析与推演…':analysis?'重新运行 AI 审查':'运行 AI 审查'}</Button></div>{snapshot.mode!=='server'&&<div className="al-note"><Icon name="info"/><p>请连接服务端后运行；当前页面不会用预设文本冒充模型结果。</p></div>}{analysis&&<>{analysis.planRevision!==p.revision&&<div className="al-note warning"><Icon name="alert"/><p>计划已变更，这份 Copilot 结果属于 v{analysis.planRevision}；请重新运行后再参考。</p></div>}<div className="al-copilot-meta"><span className={`al-copilot-live ${analysis.degraded?'degraded':''}`}><i/> {analysis.degraded?'模型不可用 · 规则降级解释':'模型辅助解释'}</span><span>{analysis.provider}{analysis.model?` · ${analysis.model}`:''}</span><span>解析器 {analysis.parser}</span><span>规则包 {analysis.ruleVersion}</span></div>{analysis.copilot&&<AICopilotFlow analysis={analysis} packet={analysis.copilot} onTask={onTask} onBranch={onBranch} onApproval={onApproval}/>}<pre className="al-ai-summary">{analysis.summary}</pre>{analysis.copilot?<AICopilotPacket packet={analysis.copilot} workspace={w} onLine={lineNumber=>{setTab('review');setLine(lineNumber)}} onSelect={onSelect} onTask={onTask} onBranch={onBranch} onApproval={onApproval}/>:<div className="al-note"><Icon name="info"/><p>当前服务端只返回文本结果；刷新服务端后可启用结构化 AI 审查面板。</p></div>}<div className="al-copilot-rules"><h3>确定性规则结果</h3><p className="al-muted">这些规则约束资源、证据和审批边界，不被模型改写。</p>{analysis.results.map(r=><div className={`al-check-row ${r.passed?'pass':'unknown'}`} key={r.rule_id}><Icon name={r.passed?'check':'alert'} size={17}/><div><b>{r.rule_id} · {r.passed?'满足':'待进一步核对'}</b><p>{r.recommended_control||r.message}</p><small>{r.source} · {r.rule_version}</small></div></div>)}</div></>}{!analysis&&!analyzing&&<Empty title="尚未运行 AI 审查" detail="点击上方按钮，系统会执行‘理解 → 推演 → 补证 → 放行’闭环，不会修改计划。"/>}</section>}
 {tab==='branches'&&<div className="al-branch-grid">{w.branches.filter(b=>b.planId===p.id).map(b=>{const stale=b.baseRevision!==p.revision||b.baseBasis!==basis(w,p);return <article key={b.id} className="al-saved-branch"><Icon name="graph" size={23}/><h3>{b.name}</h3><Badge tone={stale?'amber':'blue'}>{stale?'基线已改变':'独立候选'}</Badge><p>基于计划 v{b.baseRevision} · {b.reservations.length} 项使用安排</p>{b.reservations.map(r=><small key={r.id}>{r.equipmentId} · {dateText(r.start)}—{timeText(r.end)}</small>)}<Button disabled={stale} primary onClick={()=>run({type:'apply_branch',payload:{id:b.id}})}>提交为新修订</Button></article>})}{!w.branches.some(b=>b.planId===p.id)&&<Empty title="尚未保存候选方案" detail="从当前计划复制候选，修改资源或时间后比较检查结果。"><Button primary onClick={onBranch}>创建候选方案</Button></Empty>}</div>}
 {tab==='history'&&<div className="al-history-layout"><section className="al-table-panel"><h3>操作记录</h3><History workspace={w} objectId={p.id}/></section><section className="al-table-panel"><h3>人工复核记录</h3>{w.decisions.filter(d=>d.planId===p.id).map(d=><article className="al-decision" key={d.id}><Badge tone={d.basis===basis(w,p)?'blue':'amber'}>{d.basis===basis(w,p)?'适用当前版本':'不适用当前版本'}</Badge><h4>{d.actor} · v{d.revision}</h4><p>{d.comment}</p><small>{dateText(d.at)}</small></article>)}{!w.decisions.some(d=>d.planId===p.id)&&<Empty title="还没有复核记录" detail="所有已登记条件满足后，由服务端记录当前版本的人工复核。"/>}</section></div>}
 </>
}
 function AICopilotFlow({analysis,packet,onTask,onBranch,onApproval}:{analysis:Analysis;packet:CopilotPacket;onTask:()=>void;onBranch:()=>void;onApproval:()=>void}){
  const stages=[
   {label:'理解 SOP',meta:`${packet.entities.steps} 步 · ${packet.entities.substances.length} 种化学品`,tone:'done',icon:'spark'},
   {label:'风险推演',meta:`${packet.riskSignals.length+packet.conflicts.length} 个信号 · ${packet.ruleSummary.blocked} 项阻断`,tone:packet.ruleSummary.blocked?'alert':'done',icon:'alert'},
   {label:'证据闭环',meta:`${packet.evidenceGaps.length} 个缺口 · ${packet.nextActions.length} 个动作`,tone:packet.evidenceGaps.length?'attention':'done',icon:'file'},
   {label:'人工放行',meta:packet.ruleSummary.blocked?'安全门关闭':'等待安全负责人确认',tone:packet.ruleSummary.blocked?'locked':'ready',icon:'shield'},
  ]
  return <section className="al-ai-flow"><header><div><span className="al-eyebrow">AI + SCENARIO INNOVATION</span><h3>把一段实验计划，推成一条可审查的决策链</h3><p>模型负责理解与生成候选，规则负责约束，人工负责人负责最终放行。每一步都能回到原文、资源或证据。</p></div><div className="al-ai-flow-model"><span className={analysis.degraded?'offline':''}/>{analysis.degraded?'规则降级可用':`${analysis.provider} · ${analysis.model||'模型'}`}</div></header><div className="al-ai-flow-steps">{stages.map((stage,index)=><div className={`al-ai-flow-step ${stage.tone}`} key={stage.label}><span className="al-ai-flow-icon"><Icon name={stage.icon} size={16}/></span><div><b>{stage.label}</b><small>{stage.meta}</small></div>{index<stages.length-1&&<i/>}</div>)}</div><footer><span><Icon name="shield" size={15}/>候选方案在隔离副本中推演，AI 不会自动改写或批准正式计划。</span><div><Button icon="file" onClick={onTask}>转为补证任务</Button><Button icon="graph" onClick={onBranch}>打开方案推演</Button><Button primary icon="shield" onClick={onApproval}>进入人工放行</Button></div></footer></section>
 }
 function AICopilotPacket({packet,workspace,onLine,onSelect,onTask,onBranch,onApproval}:{packet:CopilotPacket;workspace:Workspace;onLine:(line:number)=>void;onSelect:(s:NonNullable<Selection>)=>void;onTask:()=>void;onBranch:()=>void;onApproval:()=>void}){
 const [view,setView]=useState<'understand'|'risk'|'evidence'|'scenarios'>('understand')
 const entity=packet.entities
 const tabs:[typeof view,string,string][]=[['understand','理解结果','spark'],['risk','风险与冲突','alert'],['evidence','证据与动作','file'],['scenarios','方案推演','graph']]
 const resourceName=(id?:string|null)=>id?workspace.equipment.find(e=>e.id===id)?.name||id:''
 return <div className="al-copilot-packet">
  <div className="al-copilot-overview"><div className="al-copilot-kpi"><strong>{entity.steps}</strong><span>步骤已解析</span></div><div className="al-copilot-kpi"><strong>{entity.hazards.length}</strong><span>风险信号</span></div><div className="al-copilot-kpi"><strong>{packet.conflicts.length}</strong><span>资源冲突</span></div><div className="al-copilot-kpi"><strong>{packet.evidenceGaps.length}</strong><span>证据缺口</span></div><div className="al-copilot-kpi accent"><strong>{packet.scenarios.length}</strong><span>候选方案</span></div></div>
  <div className="al-copilot-tabs" role="tablist">{tabs.map(([id,label,icon])=><button key={id} role="tab" aria-selected={view===id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon name={icon} size={15}/>{label}{id==='risk'&&packet.conflicts.length>0?<b>{packet.conflicts.length}</b>:null}{id==='evidence'&&packet.evidenceGaps.length>0?<b>{packet.evidenceGaps.length}</b>:null}</button>)}</div>
  {view==='understand'&&<div className="al-copilot-grid"><section className="al-copilot-card"><header><div><span className="al-eyebrow">STRUCTURED UNDERSTANDING</span><h3>AI 看见了什么</h3></div><Badge tone="blue">可追溯</Badge></header><div className="al-chip-row">{entity.substances.length?entity.substances.map((s,i)=><span className="al-copilot-chip" key={String(s.name||i)}><Icon name="flask" size={13}/>{String(s.name||'化学品')}</span>):<span className="al-copilot-chip muted">原文未出现已知化学品名称</span>}{entity.ppe.map(item=><span className="al-copilot-chip" key={item}><Icon name="shield" size={13}/>{item}</span>)}{entity.ventilation&&<span className="al-copilot-chip"><Icon name="resources" size={13}/>{entity.ventilation}</span>}</div><div className="al-copilot-facts"><div><span>设备语义</span><b>{entity.equipment.length?entity.equipment.join('、'):'待从原文确认'}</b></div><div><span>废物流向</span><b>{entity.wasteStreams.length?entity.wasteStreams.join('、'):'未识别'}</b></div><div><span>文本规则</span><b>{packet.ruleSummary.pass} 满足 · {packet.ruleSummary.unknown} 待确认 · {packet.ruleSummary.blocked} 阻断</b></div></div></section><section className="al-copilot-card"><header><div><span className="al-eyebrow">RISK EXPLANATION</span><h3>为什么需要关注</h3></div><Icon name="spark" size={18}/></header>{packet.riskSignals.slice(0,4).map(item=><button className="al-copilot-row" key={item.id} onClick={()=>item.line ? onLine(item.line) : item.step&&onLine(item.step)}><span className={`al-copilot-severity ${item.severity||'medium'}`}/><div><b>{item.title}</b><small>{item.detail}</small>{item.controls?.length?<em>控制：{item.controls.join('、')}</em>:null}</div><Icon name="arrow" size={14}/></button>)}{!packet.riskSignals.length&&<div className="al-copilot-empty"><Icon name="check"/><span>当前文本未形成额外风险信号，仍需完成资源和证据核验。</span></div>}</section></div>}
  {view==='risk'&&<div className="al-copilot-list"><div className="al-copilot-section-head"><div><span className="al-eyebrow">CONFLICT MAP</span><h3>冲突如何阻断实验</h3></div><Button icon="graph" onClick={onBranch}>进入方案推演</Button></div>{packet.conflicts.map(item=><article className="al-copilot-alert blocked" key={item.id}><div className="al-copilot-alert-icon"><Icon name="alert" size={18}/></div><div><b>{item.title}</b><p>{item.detail}</p><small>{item.equipmentId?`资源 ${resourceName(item.equipmentId)} · `:''}{item.relatedPlanIds?.length?`关联计划 ${item.relatedPlanIds.join('、')}`:'当前计划'}</small></div><div className="al-copilot-alert-actions">{item.equipmentId&&<button onClick={()=>onSelect({type:'equipment',id:item.equipmentId!})}>定位资源</button>}{item.line&&<button onClick={()=>onLine(item.line!)}>原文 L{item.line}</button>}</div></article>)}{!packet.conflicts.length&&<div className="al-copilot-empty"><Icon name="check"/><span>当前资源检查没有硬阻断；未知项仍需处理。</span></div>}<div className="al-copilot-section-head secondary"><div><span className="al-eyebrow">TEXT RULE SIGNALS</span><h3>文本层风险</h3></div></div>{packet.riskSignals.map(item=><article className="al-copilot-alert" key={item.id}><div className={`al-copilot-alert-icon ${item.severity||'medium'}`}><Icon name="spark" size={16}/></div><div><b>{item.title}</b><p>{item.detail}</p></div>{item.step&&<button onClick={()=>onLine(item.line || item.step!)}>定位步骤</button>}</article>)}</div>}
  {view==='evidence'&&<div className="al-copilot-list"><div className="al-copilot-section-head"><div><span className="al-eyebrow">EVIDENCE CLOSURE</span><h3>补什么，谁来补</h3></div><Button primary icon="plus" onClick={onTask}>创建补证任务</Button></div>{packet.evidenceGaps.map(item=><article className="al-copilot-evidence" key={item.id}><span className={`al-copilot-priority ${item.priority||'medium'}`}>{item.priority==='high'?'高':'中'}</span><div><b>{item.title}</b><p>{item.detail}</p><small>{item.equipmentId?`关联 ${resourceName(item.equipmentId)} · `:''}{item.line?`原文 L${item.line}`:'计划级检查'}</small></div><Icon name="arrow" size={15}/></article>)}{!packet.evidenceGaps.length&&<div className="al-copilot-empty"><Icon name="check"/><span>当前没有识别到证据缺口，请继续进行人工复核。</span></div>}<div className="al-copilot-next-actions"><div className="al-copilot-section-head secondary"><div><span className="al-eyebrow">NEXT ACTIONS</span><h3>AI 已经排好下一步</h3></div></div>{packet.nextActions.slice(0,5).map(action=><button className="al-copilot-action-row" key={action.id} onClick={onTask}><span className="al-copilot-action-index">→</span><div><b>{action.title}</b><small>{action.detail}</small></div><em>{action.owner||'负责人'}</em></button>)}</div><div className="al-copilot-action-strip"><Icon name="spark" size={17}/><span>AI 建议将每个缺口变成可追踪任务，并保留来源与负责人。</span><Button onClick={onTask}>转为任务</Button></div></div>}
  {view==='scenarios'&&<div className="al-copilot-list"><div className="al-copilot-section-head"><div><span className="al-eyebrow">SCENARIO LAB</span><h3>先比较，再改变正式计划</h3></div><Button primary icon="graph" onClick={onBranch}>打开候选方案编辑器</Button></div><div className="al-scenario-grid">{packet.scenarios.map(scenario=><article className={`al-scenario-card ${scenario.kind} ${scenario.kind==='baseline'?'is-baseline':'is-actionable'}`} key={scenario.id} role={scenario.kind==='baseline'?undefined:'button'} tabIndex={scenario.kind==='baseline'?undefined:0} onClick={scenario.kind==='baseline'?undefined:onBranch} onKeyDown={scenario.kind==='baseline'?undefined:e=>{if(e.key==='Enter'||e.key===' ')onBranch()}}><header><div><b>{scenario.name}</b><small>{scenario.status==='current'?'正式基线':'AI 建议候选'}</small></div><Badge tone={scenario.counts.blocked?'red':scenario.counts.unknown?'amber':'green'}>{scenario.counts.blocked?'有阻断':scenario.counts.unknown?'待补证':'条件满足'}</Badge></header><p>{scenario.summary}</p><div className="al-scenario-counts"><span><b>{scenario.counts.blocked}</b>阻断</span><span><b>{scenario.counts.unknown}</b>待确认</span><span><b>{scenario.counts.pass}</b>满足</span></div>{scenario.changes.length>0&&<div className="al-scenario-changes">{scenario.changes.slice(0,3).map((change,i)=><small key={i}>{String(change.reason||change.action||`${change.from||''} → ${change.to||''}`)}</small>)}</div>}{scenario.kind!=='baseline'&&<span className="al-scenario-open">点击打开隔离方案 →</span>}</article>)}</div><div className="al-note"><Icon name="shield" size={17}/><p>候选方案在隔离副本中计算；只有人工提交后才会形成新修订，不会因为 AI 推荐自动放行。</p></div></div>}
 </div>
}
function Settings({api,w,reduced,setReduced,onInitialize,onAddLab}:{api:ReturnType<typeof useWorkspace>;w:Workspace;reduced:boolean;setReduced:(v:boolean)=>void;onInitialize:()=>void;onAddLab:()=>void}){
 const [token,setToken]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(false)
 const connect=async()=>{setPending(true);setSessionToken(token);try{await api.connect();setMessage('已连接服务端。浏览器草稿仍保存在原处，没有自动覆盖服务器数据。');setToken('')}catch(e){setMessage(e instanceof Error?e.message:'连接失败。')}finally{setPending(false)}}
 return <div className="al-content-page al-settings-page"><PageTitle eyebrow="WORKSPACE SETTINGS" title="工作区设置" detail="网页通过浏览器访问；前端页面与服务端各司其职，不需要桌面客户端。"/><div className="al-settings-grid"><section className="al-settings-card"><span className="al-mini-icon"><Icon name="link"/></span><h2>连接与数据位置</h2><p>当前：{api.snapshot.mode==='server'?'服务端持久化记录':'此浏览器的本地草稿'}。两份存档相互隔离，连接失败不会自动替换已有记录。</p><Field label="工作区访问令牌（部署方启用时填写）" hint="令牌只保留在页面内存，不写入网址或本地存储。"><input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="本机开发可留空"/></Field><div className="al-actions"><Button primary disabled={pending} onClick={connect}>{pending?'正在连接…':'连接服务端'}</Button><Button onClick={()=>{api.openLocal();setMessage('已切换到此浏览器草稿，不改变服务端记录。')}}>打开浏览器草稿</Button><Button icon="reset" title="刷新当前存档" onClick={()=>api.refresh().catch(e=>setMessage(String(e)))}/></div>{message&&<div className="al-inline-message" role="status">{message}</div>}<div className="al-note"><Icon name="shield" size={18}/><p>当前实现为单一工作区负责人访问，不冒充机构 SSO 或多角色授权。公网部署前必须配置访问控制及 HTTPS。</p></div></section><section className="al-settings-card"><span className="al-mini-icon"><Icon name="export"/></span><h2>记录与备份</h2><p>导出包含计划、设备、证据、候选方案和操作记录；不是安全合格证明。</p><dl className="al-property-list"><div><dt>工作区版本</dt><dd>v{w.revision}</dd></div><div><dt>规则包</dt><dd>{RULE_PACK}</dd></div><div><dt>数据来源</dt><dd>{w.provenance==='example'?'明确标记的示例工作区':'用户录入'}</dd></div><div><dt>交付形式</dt><dd>浏览器网页系统</dd></div></dl><div className="al-actions"><Button primary icon="export" onClick={()=>exportJson(w,`aegislab-workspace-v${w.revision}.json`)}>导出当前工作区</Button><Button onClick={()=>{const raw=api.exportRaw();if(raw)exportJson({rawBrowserArchive:raw},'aegislab-browser-recovery.json');else setMessage('此浏览器没有单独的草稿存档。')}}>导出浏览器原始存档</Button></div></section><section className="al-settings-card"><span className="al-mini-icon"><Icon name="eye"/></span><h2>交互与可访问性</h2><label className="al-switch-row"><div><b>减少动态效果</b><small>关闭连线流动和过渡，保留全部业务操作。</small></div><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/></label><p>三维不可用时自动提供二维平面。关系图、原文、任务与复核不依赖 GPU。</p></section><section className="al-settings-card"><span className="al-mini-icon"><Icon name="cube"/></span><h2>实验室配置</h2><p>不同实验室拥有自己的布局和设备，原文与资源依赖不写死在样例中。</p><div className="al-actions"><Button icon="plus" onClick={onAddLab}>建立实验室</Button>{!w.laboratories.length&&<Button onClick={onInitialize}>导入示例工作区</Button>}</div><p className="al-muted">不设置“评委模式”“开始演示”或自动批准入口；比赛视频独立于产品。</p></section></div></div>
}
